MySample/MySample/MySample/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySample/MySample/customer/urls.py
from django.urls import path
from django.views.generic import View, TemplateView
from . import views 
from .v1 import views as v1Views

app_name = 'landing'

urlpatterns = [
    path('index/', views.CustomerIndexView.as_view(), name="index_view"),
    path('registration/', views.CustomerRegistrationView.as_view(), name="registration_view"),
    path('v1/customers/', v1Views.CustomersView.as_view()),
    path('v1/customers/<str:user_id>',v1Views.CustomersView.as_view()),
    
    # path('dashboard/', views.CustomerDashboardView.as_view(), name="index_view"),

]

MySample/MySample/dashboard/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .v1 import views as v1Views

app_name = 'dashboard'
urlpatterns = [
    path('product', views.DashboardProductView.as_view(), name="product_view"),
    path('product/register', views.ProductRegistrationView.as_view(), name="register_view"),
    path('customer/', views.DashboardCustomerView.as_view(), name="customer"),
    path('customer/registration', views.DashboardCustomerRegistrationView.as_view(), name="customer_view"),
    path('buy/', views.BuyView.as_view(), name="buy"),
    
    path('v1/products',v1Views.ProductsView.as_view()),
    path('v1/products/<str:product_id>',v1Views.ProductsView.as_view()),
    path('v1/orders',v1Views.OrdersView.as_view()),
    path('v1/orders/<str:order_id>',v1Views.OrdersView.as_view()),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySample/MySample/customer/v1/views.py
from lib2to3.pgen2 import driver
from multiprocessing import context
from rest_framework.serializers import Serializer
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
#change this later
from dashboard.models import Person
from customer.v1 import serializers
from rest_framework import status as request_status
from rest_framework.authtoken.models import Token
from dashboard.models import Customer
from rest_framework import authentication, permissions
from rest_framework.pagination import LimitOffsetPagination
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend
 

class CustomersView(GenericAPIView):
    serializer_class = serializers.CustomersSerializer
    # authentication_classes = [authentication.TokenAuthentication]
    queryset = Customer.objects.all()
    pagination_class = LimitOffsetPagination
    filter_backends = [DjangoFilterBackend,filters.SearchFilter]
    filterset_fields={
        'isDeleted':['exact','iexact'],
        'dateregistered':['exact','iexact','lte','gte'],
        'address':['exact','iexact','contains'],
        'username':['exact','iexact','contains']
    }
    search_fields = ['username','firstName', 'lastName']
    
    """Create only if user is admin"""
    
    # add later
    # permission_classes = [IsNotAuthenticatedDenyGet]
    
    def post(self,request,user_id=None,format=None): 
        """No POST for single user query"""
        if user_id != None:
            return Response({'detail':'Method POST not allowed'},status=request_status.HTTP_405_METHOD_NOT_ALLOWED)
        
        """A new user signs up"""
        data = request.data
        if type(request.data) == dict:
            data = [data]
        serializer = self.serializer_class(data = data,many=True)
        if serializer.is_valid():
            serializer.save()
            
            """make a token here"""
            # user = Person.objects.get(username=serializer.validated_data.get('username'))
            # token:Token = Token.objects.create(user=user)
            # token_key = token.key
            
            """when token is availabel"""
            # return Response({"user":serializer.data,"token":token_key})

            return Response({"user":serializer.data})
        
        return Response(serializer.errors, status=request_status.HTTP_400_BAD_REQUEST)

    def get(self,request,user_id=None,format=None):
        
        """Get all users. Only allow if user is authenticated."""
        if user_id == None:
            queryset = self.filter_queryset(self.get_queryset())
            page = self.paginate_queryset(queryset)
            serializer = self.serializer_class(page,many=True,context={'request':request})
            return self.get_paginated_response(serializer.data)
        
        return self.get_single_user(request,user_id)
    
    def get_single_user(self,request,user_id):
        response:Response = None
        user_exists,user_queryset = self.check_user_exists_with_user_id(user_id)
        if not user_exists:
            response = Response({"detail":"User does not exist"},status = request_status.HTTP_404_NOT_FOUND)
        else:
            """if user is authenticated show all filtered details, else send unauthorized access"""
            # if request.user.is_authenticated:
            #     queryset = self.filter_queryset(user_queryset)
            #     serializer = self.serializer_class(queryset.first(),context={'request':request})
            #     response = Response(serializer.data)    
            # else:
            #     response = Response({"detail":"Unauthorized Access"}, status=request_status.HTTP_401_UNAUTHORIZED)
            """used for testing"""
            queryset = self.filter_queryset(user_queryset)
            serializer = self.serializer_class(queryset.first(),context={'request':request})
            response = Response(serializer.data)
        return response
    
    def check_user_exists_with_user_id(self,user_id):
        exists = True
        user_queryset=None
        user_queryset = self.get_queryset().filter(id=user_id)
        if len(user_queryset) == 0:
            exists = False
        return exists,  user_queryset
    
    def patch(self,request,user_id=None,format=None):
        if user_id is None:
            return Response({'detail':'Method PATCH not allowed'},status=request_status.HTTP_405_METHOD_NOT_ALLOWED)
                
        response:Response = None
        user_exists,user_queryset = self.check_user_exists_with_user_id(user_id)
        if not user_exists:
            response = Response({"detail":"User does not exist"},status = request_status.HTTP_404_NOT_FOUND)
        else:
            user = user_queryset.first()
            serializer = serializers.CustomersSerializer(user,data=request.data,partial=True)
            if serializer.is_valid():
                serializer.save()
                response = Response(serializers.CustomersSerializer(user).data)
            else:
                response = Response(serializer.errors, status=request_status.HTTP_400_BAD_REQUEST)
        return response
    
    def put(self,request,user_id=None,format=None):
        data = request.data 
        if type(data) == dict:
            if 'id' not in data:
                data['id'] = user_id
            data=[data]
        valid_data=[]
        for d in data:
            if 'id' in d:
                valid_data.append(d)
        ids = []
        for d in valid_data:
            ids.append(d['id'])
        user_queryset = Customer.objects.filter(id__in=ids)
        response:Response=None
        if len(user_queryset) == 0:
            response = Response({"detail":"No user matching the specified id/s are found"},status = request_status.HTTP_404_NOT_FOUND)
        else:    
            serializer = serializers.CustomersSerializer(user_queryset,data=valid_data,many=True)
            if serializer.is_valid():
                serializer.save()
                response = Response(serializer.data)
            else:
                response = Response(serializer.errors, status=request_status.HTTP_400_BAD_REQUEST)
        return response

    def delete(self,request,user_id=None,format=None):
        data = request.data
        if type(data) == dict:
            data['id'] = user_id
            data=[data]
        valid_data=[]
        for d in data:
            if 'id' in d:
                valid_data.append(d)
        ids = []
        for d in valid_data:
            ids.append(d['id'])
        user_queryset = Customer.objects.filter(id__in=ids).update(isDeleted=True)
        message = str(user_queryset) + " Customer instance/s are deleted"
        
        return Response({"detail":message},status = request_status.HTTP_200_OK)

MySample/MySample/customer/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.
class CustomerIndexView(View):
    def get(self, request):
        return render(request, 'customer/index.html')

    def post(self, request):
        return render(request, 'customer/customer_register.html')

class CustomerRegistrationView(View):
    def get(self, request):
        return render(request, 'customer/customer_register.html')

# class CustomerDashboardView(View):
#     def get(self, request):
#         return render(request, 'customer/registertable.html')

MySample/MySample/customer/templates/customer/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <script scr="js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Abril Fatface' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Alike' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <link rel="icon" type="image/png" sizes="50X50" href="{% static 'css/logoTS.png' %}">
</head>

<body>    
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'pic2.png' %}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="font-weight-normal display-1 text-white">TECHMART</h1>
                <button style="border-radius: 50px" type="button" class="btn btn-success text-white btn-lg" data-toggle="modal" data-target="#about">
                    About
                  </button>
                  <button style="border-radius: 50px" type="button" class="btn btn-warning text-white btn-lg" data-toggle="modal" data-target="#contact">
                    Contact Us
                  </button> <br>
              </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'pic3.png' %}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'pic1.png' %}" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    <div class="container my-4">
        <div class="row">
            <div class="col" style="font-family: 'Abril Fatface';font-size: 22px;">
                <h1>Best Merchandise</h1>
                <h1>You Can Find Online!</h1>
                <p style="font-family: 'ABeeZee';font-size: 18px;" class="text-justify">"TechMart's the top online shopping site in the country, has made several shifts in the e-commerce business in the Philippines, creating an avenue for sellers to promote their items online, 
                    and to give Filipinos new ways to discover and buy the best options for themselves. With seven years of quality service through their website and mobile app, its constantly growing the inventory of items, and offering convenient payment options, the true effortless shopping experience begins once again through TechMart's new platform."
                </p>
                <div>
                    <button style="border-radius: 50px" type="button" class="btn btn-outline-dark text-dark btn-lg" data-toggle="modal" data-target="#login">
                        Login
                      </button>
                </div>
            </div>

            <div class="col">
                <img src="{% static 'content.png' %}" class="rounded float-right" alt="">
            </div>
        </div>
    </div>

    <hr class="my-1">


    <!-- Modal -->
    <div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header" style="background-color: #6eb5ff;">
                    <h5 class="modal-title" id="exampleModalLongTitle">CONTACT US</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body my-4">
                    <form>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Name</label>
                            <div class="row">
                                <div class="col">
                                    <input type="text" class="form-control" placeholder="First name">
                                </div>
                                <div class="col">
                                    <input type="text" class="form-control" placeholder="Last name">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-4">
                                <label for="formGroupExampleInput">Email</label>
                                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Message</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="2" placeholder="Your Message"></textarea>
                            </div>
                        </div>
                    </form>
                    <div class="d-flex justify-content-center text-center">
                        <a href="#" class="fa fa-facebook"></a>&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="#" class="fa fa-twitter"></a>&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="#" class="fa fa-google"></a>&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                </div>
                <div class="modal-footer">
                    <a style="border-radius: 50px;" type="button" class="btn btn-outline-info waves-effect" data-dismiss="modal">Submit</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->

     <!-- Modal -->
     <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header" style="background-color: #6eb5ff;">
                    <h5 class="modal-title" id="exampleModalLongTitle">ADMIN LOGIN</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body my-4">
                    <form>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Username</label>
                            <div class="row">
                                <div class="col">
                                    <input type="text" class="form-control" placeholder="Username">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-4">
                                <label for="formGroupExampleInput">Password</label>
                                <input type="password" class="form-control" id="formGroupExampleInput" placeholder="Password">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-outline-primary btn-lg" style="border-radius: 50px" href="{% url 'dashboard:customer_view' %}" role="button">Login</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->

    <!-- Modal About-->
    <div class="modal fade" id="about" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header" style="background-color: #6eb5ff;">
                    <h5 class="modal-title" id="exampleModalLongTitle">ABOUT US</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                    <hr style="border: 1px solid black;">
                    <p style="font-family: 'Alike'; font-size: 16px; text-align:center;">"We are all very different. We were born in different cities, at different times, we love different music, food, movies. But we have something that unites us all. It is our company. We are its heart. We are not just a team, we are
                        a family."
                    </p>
                    <hr style="border: 1px solid black;">
                </div>
                <div class="modal-footer">
                    <a style="border-radius: 50px;" type="button" class="btn btn-outline-info waves-effect" data-dismiss="modal">Close</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal About-->

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>