MySample/MySample/MySample/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySample/MySample/customer/urls.py
from django.urls import path
from django.views.generic import View, TemplateView
from . import views 
from .v1 import views as v1Views

app_name = 'landing'

urlpatterns = [
    path('index/', views.CustomerIndexView.as_view(), name="index_view"),
    path('registration/', views.CustomerRegistrationView.as_view(), name="registration_view"),
    path('v1/customers/', v1Views.CustomersView.as_view()),
    path('v1/customers/<str:user_id>',v1Views.CustomersView.as_view()),
    
    # path('dashboard/', views.CustomerDashboardView.as_view(), name="index_view"),

]

MySample/MySample/dashboard/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .v1 import views as v1Views

app_name = 'dashboard'
urlpatterns = [
    path('product', views.DashboardProductView.as_view(), name="product_view"),
    path('product/register', views.ProductRegistrationView.as_view(), name="register_view"),
    path('customer/', views.DashboardCustomerView.as_view(), name="customer"),
    path('customer/registration', views.DashboardCustomerRegistrationView.as_view(), name="customer_view"),
    path('buy/', views.BuyView.as_view(), name="buy"),
    
    path('v1/products',v1Views.ProductsView.as_view()),
    path('v1/products/<str:product_id>',v1Views.ProductsView.as_view()),
    path('v1/orders',v1Views.OrdersView.as_view()),
    path('v1/orders/<str:order_id>',v1Views.OrdersView.as_view()),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySample/MySample/dashboard/models.py
from django.db import models
#from django.db.models import Model
from datetime import datetime

# Create your models here.

class Product(models.Model):
    datereg = models.DateField(auto_now_add=True)
    category = models.CharField(max_length = 100)
    name = models.CharField(max_length = 100)
    brand = models.CharField(max_length = 100)
    size = models.CharField(max_length = 50)
    color = models.CharField(max_length = 50)
    stocks = models.IntegerField(max_length = 5)
    price = models.FloatField(max_length = 50)
    description = models.CharField(max_length = 10000)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    isDeleted = models.BooleanField(default=False)

    class Meta:
        db_table = "Product"

class Person(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    dateregistered = models.DateField(auto_now_add=True)
    address = models.CharField(max_length=100)
    birthdate = models.DateField(default = datetime.now())
    birthplace = models.CharField(max_length=100)
    isDeleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = "Person"

class Customer(Person):
    email = models.EmailField()
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    contact = models.CharField(max_length=11)

    class Meta:
        db_table = "Customer"


class OrderItems(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null= True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null= True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    class Meta:
        db_table = "OrderItems"
    
    

MySample/MySample/dashboard/forms.py
from django import forms
from .models import Customer
from .models import Person
from .models import *

class ProductForm(forms.ModelForm):
	
	class Meta:
		model = Product
		fields = ('category', 'name', 'brand', 'size', 'color', 'stocks', 'price', 'description', 'image')

class CustomerForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        fields = ('firstname', 'lastname',)

class PurchaseForm(forms.ModelForm):
    
    class Meta:
        model = OrderItems
        fields = ('quantity',)

MySample/MySample/customer/v1/views.py
from lib2to3.pgen2 import driver
from multiprocessing import context
from rest_framework.serializers import Serializer
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
#change this later
from dashboard.models import Person
from customer.v1 import serializers
from rest_framework import status as request_status
from rest_framework.authtoken.models import Token
from dashboard.models import Customer
from rest_framework import authentication, permissions
from rest_framework.pagination import LimitOffsetPagination
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend
 

class CustomersView(GenericAPIView):
    serializer_class = serializers.CustomersSerializer
    # authentication_classes = [authentication.TokenAuthentication]
    queryset = Customer.objects.all()
    pagination_class = LimitOffsetPagination
    filter_backends = [DjangoFilterBackend,filters.SearchFilter]
    filterset_fields={
        'isDeleted':['exact','iexact'],
        'dateregistered':['exact','iexact','lte','gte'],
        'address':['exact','iexact','contains'],
        'username':['exact','iexact','contains']
    }
    search_fields = ['username','firstName', 'lastName']
    
    """Create only if user is admin"""
    
    # add later
    # permission_classes = [IsNotAuthenticatedDenyGet]
    
    def post(self,request,user_id=None,format=None): 
        """No POST for single user query"""
        if user_id != None:
            return Response({'detail':'Method POST not allowed'},status=request_status.HTTP_405_METHOD_NOT_ALLOWED)
        
        """A new user signs up"""
        data = request.data
        if type(request.data) == dict:
            data = [data]
        serializer = self.serializer_class(data = data,many=True)
        if serializer.is_valid():
            serializer.save()
            
            """make a token here"""
            # user = Person.objects.get(username=serializer.validated_data.get('username'))
            # token:Token = Token.objects.create(user=user)
            # token_key = token.key
            
            """when token is availabel"""
            # return Response({"user":serializer.data,"token":token_key})

            return Response({"user":serializer.data})
        
        return Response(serializer.errors, status=request_status.HTTP_400_BAD_REQUEST)

    def get(self,request,user_id=None,format=None):
        
        """Get all users. Only allow if user is authenticated."""
        if user_id == None:
            queryset = self.filter_queryset(self.get_queryset())
            page = self.paginate_queryset(queryset)
            serializer = self.serializer_class(page,many=True,context={'request':request})
            return self.get_paginated_response(serializer.data)
        
        return self.get_single_user(request,user_id)
    
    def get_single_user(self,request,user_id):
        response:Response = None
        user_exists,user_queryset = self.check_user_exists_with_user_id(user_id)
        if not user_exists:
            response = Response({"detail":"User does not exist"},status = request_status.HTTP_404_NOT_FOUND)
        else:
            """if user is authenticated show all filtered details, else send unauthorized access"""
            # if request.user.is_authenticated:
            #     queryset = self.filter_queryset(user_queryset)
            #     serializer = self.serializer_class(queryset.first(),context={'request':request})
            #     response = Response(serializer.data)    
            # else:
            #     response = Response({"detail":"Unauthorized Access"}, status=request_status.HTTP_401_UNAUTHORIZED)
            """used for testing"""
            queryset = self.filter_queryset(user_queryset)
            serializer = self.serializer_class(queryset.first(),context={'request':request})
            response = Response(serializer.data)
        return response
    
    def check_user_exists_with_user_id(self,user_id):
        exists = True
        user_queryset=None
        user_queryset = self.get_queryset().filter(id=user_id)
        if len(user_queryset) == 0:
            exists = False
        return exists,  user_queryset
    
    def patch(self,request,user_id=None,format=None):
        if user_id is None:
            return Response({'detail':'Method PATCH not allowed'},status=request_status.HTTP_405_METHOD_NOT_ALLOWED)
                
        response:Response = None
        user_exists,user_queryset = self.check_user_exists_with_user_id(user_id)
        if not user_exists:
            response = Response({"detail":"User does not exist"},status = request_status.HTTP_404_NOT_FOUND)
        else:
            user = user_queryset.first()
            serializer = serializers.CustomersSerializer(user,data=request.data,partial=True)
            if serializer.is_valid():
                serializer.save()
                response = Response(serializers.CustomersSerializer(user).data)
            else:
                response = Response(serializer.errors, status=request_status.HTTP_400_BAD_REQUEST)
        return response
    
    def put(self,request,user_id=None,format=None):
        data = request.data 
        if type(data) == dict:
            if 'id' not in data:
                data['id'] = user_id
            data=[data]
        valid_data=[]
        for d in data:
            if 'id' in d:
                valid_data.append(d)
        ids = []
        for d in valid_data:
            ids.append(d['id'])
        user_queryset = Customer.objects.filter(id__in=ids)
        response:Response=None
        if len(user_queryset) == 0:
            response = Response({"detail":"No user matching the specified id/s are found"},status = request_status.HTTP_404_NOT_FOUND)
        else:    
            serializer = serializers.CustomersSerializer(user_queryset,data=valid_data,many=True)
            if serializer.is_valid():
                serializer.save()
                response = Response(serializer.data)
            else:
                response = Response(serializer.errors, status=request_status.HTTP_400_BAD_REQUEST)
        return response

    def delete(self,request,user_id=None,format=None):
        data = request.data
        if type(data) == dict:
            data['id'] = user_id
            data=[data]
        valid_data=[]
        for d in data:
            if 'id' in d:
                valid_data.append(d)
        ids = []
        for d in valid_data:
            ids.append(d['id'])
        user_queryset = Customer.objects.filter(id__in=ids).update(isDeleted=True)
        message = str(user_queryset) + " Customer instance/s are deleted"
        
        return Response({"detail":message},status = request_status.HTTP_200_OK)

MySample/MySample/customer/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.
class CustomerIndexView(View):
    def get(self, request):
        return render(request, 'customer/index.html')

    def post(self, request):
        return render(request, 'customer/customer_register.html')

class CustomerRegistrationView(View):
    def get(self, request):
        return render(request, 'customer/customer_register.html')

# class CustomerDashboardView(View):
#     def get(self, request):
#         return render(request, 'customer/registertable.html')

MySample/MySample/dashboard/templates/buy.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
                  
                <!--bootstrap-table CSS-->
                <link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
                <link href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet">

                <!-- Favicon icon -->
                <link rel="icon" type="image/png" sizes="50X50" href="{% static 'css/logoTS.png' %}">
                
                <!-- Custom CSS for UI-->
                <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
                <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet"/>
                

                <!-- form validation -->
                <script type="text/javascript" src = "{% static 'js/form-validation.js' %}"></script>
                <script type="text/javascript" src = "{% static 'js/bootstrap.bundle.min.js' %}"></script>

                <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.2/css/bootstrapValidator.min.css"/>
                <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.2/js/bootstrapValidator.min.js">
                </script>
                <style>
                    .dataTables_filter {
                       display: none;
                    }
                </style>
                
               
                </div>
                    
                    <div class="container mb-2 mt-2">  
                    
                    <table 
                            id="table" 
                            class="display table"
                            data-toggle = "table"
                            data-pagination = "true"

                            data-search = "true"
                            data-search-align = "left"
                            data-show-column = "true"
                            data-show-toggle = "false"
                            data-show-fullscreen = "false"
                            data-show-refresh = "false"
                            data-show-pagination-switch = "true"
                            data-pagination-pre-text = "Previous"
                            data-pagination-next-text = "Next"
                            data-pagination-h-align = "left"
                            data-pagination-detail-h-align = "right"
                            data-page-list = "[5, 10, 20, All]"
                            
                            data-show-export ="false"
                            style="size:100%">

                      <thead class="bg-info text-white">
                          <tr>
                              <th  data-field="category" data-sortable="false" data-switchable="false">Category</th>
                              <th  data-field="image" data-sortable="false" data-switchable="false">Photos</th>
                              <th data-field="brand" data-sortable="false" data-switchable="false">Product</th>
                              <th data-field="name" data-sortable="false" data-switchable="false">Description</th>
                              <th  data-field="price" data-sortable="false" data-switchable="false">Price</th>
                              <th data-field="edit" data-sortable="false" data-switchable="false">Transaction</th>
                          </tr>
                      </thead>
                      <tbody>
                        
                        {% for prod in products %}                          
                        <tr>
                            <td>{{prod.category}}</td>
                            <td>
                                {% if prod.image %}
                                <img src="{{prod.image.url}}" alt="photo" id = "image" width="160px" height="170px" style="border-radius: 8px; border: 1px solid #ddd; padding: 5px;" />
                                  <!--<img src="{% static 'images/honor8x.jpg' %}" width="60px" height="70px" style="border-radius: 8px; border: 1px solid #ddd; padding: 5px;"/>-->
                                {% else %}
                                  <img src="{% static 'images/default.png' %}" width="160px" height="170px" tyle="border-radius: 8px; border: 1px solid #ddd; padding: 5px;"/><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                {% endif %}
                            </td>
                            <td><strong>{{prod.name}} ({{prod.brand}})</strong></td>
                            <td>{{prod.description}}, {{prod.size}}, {{prod.color}}</td>
                            <td>Php {{prod.price|floatformat:2}}</td>
                            
                            <td>
                                <button class="btn btn-primary" href="#" style="padding: 10px;" data-toggle="modal" data-target="#newModal-{{prod.id}}"
                                >PURCHASE</button>
                                <!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{prod.id}}">
                                  DELETE
                                </button>-->
                            </td>
                        </tr>
                        <!-- Modal VIEW-->
                        <div class="modal fade" id="newModal-{{prod.id}}" tabindex="-1" role="dialog" aria-labelledby="newModalLabel" aria-hidden="true">
                            <div class="modal-dialog " role="document">
                            <div class="modal-content">
                                <div class="modal-header  bg-color--gray" >
                                  <h5 class="modal-title" style="color:Black"> Your Cart </h5>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                
                                </div>
                                
                                <form class="needs-validation" action="" id="form2" method="POST" autocomplete="off" enctype="multipart/form-data">
                                {% csrf_token %}
                                    <div class="modal-body">
                                        <input type="text" name="prod-id" value = {{prod.id}} hidden>
                                        
                                        <div class="row">
                                                <div class="col-md-5 mb-3">
                                                    <label for="">Product</label>
                                                    <br>
                                                    {{ prod.name }}
                                                </div>
                                                <div class="col-md-3 mb-3">
                                                  <label for="">Quantity</label>
                                                  
                                                  <Select class="form-control" id="id-quantity" name="prod-quantity" value = '1'>
                                                            
                                                            <option> 1 </option>
                                                            <option> 2 </option>
                                                            <option> 3  </option>
                                                            <option> 4  </option>
                                                            <option> 5 </option>              
                                                  </Select>

                                                </div>
                                                <div class="col-md-5 mb-3">
                                                    <label for="">Price per Product</label>
                                                    <br>
                                                    {{ prod.price }}
                                                </div>
                                        </div>
                                        
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCEL</button>
                                      <button type="submit" id = "btnPurchase" name = "btnPurchase"  class="btn btn-primary">BUY</button>
                                    </div>  
                                </form>
                            </div>
                            </div>
                        </div>
                        {% endfor %}
                        
                      </tbody>
                      
                      </table>
                    </div>
                
                
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
            </div>
            <footer class="footer text-center text-muted">
                <!-- <form id="form1" action="" method="POST" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" id = "btnCart" name = "btnCart" class="btn btn-primary">
                          View Cart 
                </button>
              </form> -->
                
                <p style="margin-top: 50px">All Rights Reserved by Techmart.  </p>
            </footer>
            
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#form2').bootstrapValidator();
        });
    </script>

    <!-- Scripts Datatable-->
    <script src = "https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.js"></script>

    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <!--
    <script src="https://unpkg.com/libs/jsPDF.min.js"></script>
    <script src="https://unpkg.com/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.17.1/bootstrap-table.min.js"></script>
    <!--<script src="extensions/print/bootstrap-table-print.min.js"></script>-->
    <script src="{% static 'js/bootstrap-table-export.min.js' %}"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    
    

 <!-- data table -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        
        <!-- default -->
        <!--<script>
          $('#table').dataTable( {
                paging: false,
                info: false,
            });
          $(".dataTables_info").hide();
        </script>-->

        <script>
         
          $('#table').dataTable( {
                paging: false,
                info: false,
                columnDefs: [
                    { visible: false, targets: 0 },
                    
                ],
                order: [[ 0, 'asc']],
                displayLength: 25,
                drawCallback: function ( settings ) {
                    var api = this.api();
                    var rows = api.rows( {page:'current'} ).nodes();
                    var last = null;

                    api.column(0, {page:'current'}).data().each( function (group, i){
                        if( last !== group ){
                            $(rows).eq( i ).before(
                                '<tr class="bg-light text-dark"> <td colspan="5">'+group+'</td></tr>'
                            );
                        }
                        last = group;
                    });
                }
            });
          $(".dataTables_info").hide();
        </script>

        <!-- by category -->
        <!--<script>
          $('#table').dataTable( {
                paging: false,
                info: false,
            });
          $(".dataTables_info").hide();
        </script>-->

        
    
{% endblock content %}

MySample/MySample/dashboard/templates/cart.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
     

	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'dashboard:buy' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>3</strong></h5></th>
						<th><h5>Total:<strong> $42</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-warning" href="#">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{% static 'images/default.png' %}"></div>
					<div style="flex:2"><p>Product 1</p></div>
					<div style="flex:1"><p>$20</p></div>
					<div style="flex:1">
						<p class="quantity">2</p>
						<div class="quantity">
							<img class="chg-quantity" src="{% static  'images/up.png' %}">
					
							<img class="chg-quantity" src="{% static  'images/down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>$32</p></div>
				</div>
				{% endfor %}

			</div>
		</div>
	</div>
{% endblock content %}

MySample/MySample/dashboard/templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Techmart</title>
        <!-- Favicon icon -->
    	<link rel="icon" type="image/png" sizes="50X50" href="{% static 'css/logoTS.png' %}">

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

        <!-- CSS only -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

		
     </head>
     <body>
     
        <nav class="navbar navbar-expand-lg navbar-dark bg-white">
		  <a class="navbar-brand" href="{% url 'dashboard:customer' %}">TechMart
      <img src="{% static 'css/logoTS.png' %}" alt="homepage" class="dark-logo" style="margin-left: -85px;" width ="60px" height="65"/>
      <img src="{% static 'css/text-logoTS.png' %}" alt="homepage" class="dark-logo" width ="150px" height="80" style="margin-left: 0px; padding: 0px;"/>
      </a>
    </nav>

		<div class="page-breadcrumb">
                
                <div class='navbar-nav float-right mr-auto ml-3 pl-1 bg-color--gray'>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" role="alert" style="text-align: center">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message|safe }}
                        </div>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>

         <div class="container">
                <br>
                {% block content %}
                	
                {% endblock content %}
         </div>


     	<!-- JS, Popper.js, and jQuery -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
     </body>
</html>